#============ Filebeat inputs ============
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/apache2/access.log
    - /var/log/apache2/error.log

#============ Filebeat modules ============
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

#============ Elasticsearch template setting ============
setup.template.settings:
  index.number_of_shards: 3

#============ General ============
name: web01

#============ Kibana ============
setup.kibana:
  host: "10.0.0.11:5601"

#============ Elasticsearch output ============
output.elasticsearch:
  hosts: ["10.0.0.11:9200"]

#============ Processors ============
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~