version: '3.7'
services:

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.4.2'
    ports:
    - '9200:9200'
    environment:
    - discovery.type=single-node
    - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    - LOGSPOUT=ignore
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  kibana:
    image: 'kibana:6.4.1'
    ports:
      - '5601:5601'
    volumes:
      - ./kibana/:/usr/share/kibana/config:ro

  filebeat:
    user: root
    image: "docker.elastic.co/beats/filebeat:6.7.1"
    environment:
    - setup.kibana.host=kibana:5601
    - output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes:
      - ./kibana/:/usr/share/kibana/config:ro
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
    command:
      - -e
      - --modules
      - system
      - --strict.perms=false

volumes:
  elastic_data:
